import type { Metadata } from "next";
import { Toaster } from "sonner";



export const metadata: Metadata = {
  title: "Login",
  description: "Generated by next",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
        {children}
        <Toaster
          richColors
          
          position="top-center"
          toastOptions={{
            duration: 3000,
          }}
        />
      </body>
      
    </html>
  );
}
